# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('bumplimit', models.IntegerField()),
                ('title', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('img', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='thread',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('id_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='id_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.thread'),
        ),
    ]
