# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id_thread',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='id_board',
            new_name='board',
        ),
    ]
