# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20170730_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
