# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20170802_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_to',
            field=models.ManyToManyField(to='boards.Post'),
        ),
    ]
