# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_post_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reply_to',
            field=models.ManyToManyField(blank=True, to='boards.Post'),
        ),
    ]
